apiVersion: v1
kind: Secret
metadata:
  name: app-credentials
  namespace: istio-demo
type: Opaque
stringData:
  REACT_APP_AUTH0_CALLBACK_URL: http://localhost/callback
  REACT_APP_AUTH0_CLIENT_ID: istio-demo
  REACT_APP_AUTH0_CLIENT_SECRET: jVhjXu5fM6mGqikN0GxE1LrItPfUj8Z2
  REACT_APP_AUTH0_DOMAIN: localhost
  REACT_APP_AUTH0_AUDIENCE: istio-demo-app