apiVersion: v1
kind: Secret
metadata:
  name: app-credentials
  namespace: istio-demo
type: Opaque
stringData:
  REACT_APP_AUTH0_CALLBACK_URL: http://localhost/callback
  REACT_APP_AUTH0_CLIENT_ID: FWk1YyvGkedGQN95z26pN6ndJ4nDsdjQ
  REACT_APP_AUTH0_CLIENT_SECRET: uHSmD8mV88MGIEaKgIQD065xvTpKjLMKGtXflzcbv6urYOHDXX6jSryf1wT87oEI
  REACT_APP_AUTH0_DOMAIN: dev-u5o37olgehpj6ms5.us.auth0.com
  REACT_APP_AUTH0_AUDIENCE: http://istio-demo.io