apiVersion: security.istio.io/v1beta1
kind: RequestAuthentication
metadata:
  name: auth-policy-ha-web-app
  namespace: istio-demo
spec:
  selector:
    matchLabels:
      app: ha-web-app
  jwtRules:
    - issuer: "http://localhost/realms/istio-demo-app"
      jwksUri: "http://keycloak-service.istio-demo.svc.cluster.local:8079/realms/istio-demo-app/protocol/openid-connect/certs"
      outputPayloadToHeader: x-token
      fromHeaders:
        - name: Authorization
---
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: webapp-policy
  namespace: istio-demo
spec:
  action: ALLOW
  selector:
    matchLabels:
      app: ha-web-app
  rules:
    - from:
        - source:
            requestPrincipals: ["*"]