apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: logic-policy
  namespace: istio-demo
spec:
  selector:
    matchLabels:
      app: ha-logic
  action: ALLOW
  rules:
    - from:
        - source:
            principals: [ "cluster.local/ns/istio-demo/sa/web-app-sa" ]
      to:
        - operation:
            methods: ["GET"]
            paths: ["/api/get_message"]