apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: ha-external-service
  namespace: istio-demo
spec:
  hosts:
    - "*"
  gateways:
    - http-gateway
  http:
    - match:
        - uri:
            regex: "/?(.*)"
      route:
        - destination:
            host: ha-front-service
            port:
              number: 80